### ISSUE TITLE
DLL Not found

### ISSUE THREAD

**Issue by sonnyky** [mrtrizer/UnityLlamaCpp#1]
When I run the Test.prefab, I get the error: DLL not found.
When the Editor launches it always shows an error saying llama.dll is not loaded because of missing dependencies.
I'm on Windows 11. 
Can you share the native code as well?

**Comment by mrtrizer** [comment]
If you just add a package via unity Package Manager as per readme instructions, it will care about everything.

If you are manually cloning the repo, make sure git lfs is installed. 
`git lfs install`
To fetch files from git lfs
`git lfs fetch`

Most git ui like Git Kraken or SourceTree or will do this automatically.

**Comment by sonnyky** [comment]
Thanks for the response.
The title may be misleading.
The dll file is there, but Unity is not loading it because of "missing dependencies"
![image](https://github.com/mrtrizer/UnityLlamaCpp/assets/7204489/3f61f874-eb58-4025-9f7e-16eef0b3dc40)

If we go ahead and run the project, it will spawn the dll not found error.
![image](https://github.com/mrtrizer/UnityLlamaCpp/assets/7204489/17d7c61d-7a5e-4ec2-b019-090360ec8ae5)

**Comment by brwinkle** [comment]
I'm having the same issue.

**Comment by batmanonline** [comment]
How was this DLL generated or is it just the one from llama.cpp from the official build ? 
Which llama.cpp commit ?

**Comment by sonnyky** [comment]
@batmanonline 
it is the dll that came from the official build, when doing the install from the git URL.
I assume it is the master branch? since I just followed the instructions to install from the git URL.

**Comment by mrtrizer** [comment]
Sorry everyone, for my response taking so long. I had no free time recently due to becoming a father :)

> How was this DLL generated or is it just the one from llama.cpp from the official build ? Which llama.cpp commit ?

The version is b1536 any dll from that version will work, I hope I'll have some time to update the bridge. But I recommend using https://github.com/SciSharp/LLamaSharp it has much better support that I can provide.

> @batmanonline it is the dll that came from the official build, when doing the install from the git URL. I assume it is the master branch? since I just followed the instructions to install from the git URL.

The version was b1536 and current master have different struct layouts, so if you take dll from the newest version, it won't work

**Comment by mrtrizer** [comment]
@sonnyky My bad, I forgot to add ggml_shared.dll
Fixed
