### ISSUE TITLE
Not Offloading to GPU

### ISSUE THREAD

**Issue by ShoshiOpti** [mrtrizer/UnityLlamaCpp#2]
I'm having issues offloading this project into GPU workload. I have attempted both CUDA 11 and CUDA 12 implementations, increasing and decreasing the GPU layer count and no matter what I do I am only using about 0.5GB of VRAM and 30% of my GPU (from baseline no unity open) despite the model I am using being much larger than that.

Is there something I am missing here? For reference I am running a NVDIA 3080.

**Comment by mrtrizer** [comment]
Hi, you can enable it by replacing the library files with cublas version. 
Use this exact release and it should work - https://github.com/ggerganov/llama.cpp/releases/tag/b1518 

Just drop all the dll files from [cudart-llama-bin-win-cu12.2.0-x64.zip](https://github.com/ggerganov/llama.cpp/releases/download/b1518/cudart-llama-bin-win-cu12.2.0-x64.zip) and [llama-b1518-bin-win-cublas-cu12.2.0-x64.zip](https://github.com/ggerganov/llama.cpp/releases/download/b1518/llama-b1518-bin-win-cublas-cu12.2.0-x64.zip) to Plugins folder, replacing the original dlls
